### PR TITLE
Fix SSL protocols supported by curb adapter

### PR DESCRIPTION
**Pull request by 907th**
* Use Curl:: consts instead of *magic* numbers.
* Fix invalid values of TLSv1_1 and TLSv1_2 constants.
* Add support for TLSv1_0.

### CODE REVIEW

**Comment by rogerleite** [comment]
Hi @907th. Thanks for opening this PR. Seems good to merge.

**Comment by rogerleite** [comment]
Forgot this PR sorry.
This code is going to conflict with https://github.com/savonrb/httpi/pull/208. 🤔

**Comment by ioquatix** [comment]
Can you please rebase on master? Thanks!

**Comment by 907th** [comment]
I'm closing stale issue.

**Pull request closed without merging**
