### PR TITLE
Support HTTP Basic auth in Rack adapter

### PR DESCRIPTION
**Pull request by milgner**
I wasn't sure how to best add a proper spec for this, so feel free to comment and I'll add it.

### CODE REVIEW

**Comment by rogerleite** [comment]
Hi @milgner! Thanks for the PR.

To test, you can try something like net_http spec [here](https://github.com/evopark/httpi/blob/feature/rack_basic_auth/spec/httpi/adapter/net_http_spec.rb#L101) did. Basically, you should hit a basic auth route of `IntegrationServer` and see if it's ok.

Hope that helps!

**Comment by milgner** [comment]
Hi @rogerleite, sorry for taking so long to respond and thanks for the tip. I'll write a test using `IntegrationServer` like you suggested. Should I amend the commit (to keep history clean) or make it a separate one?

**Comment by milgner** [comment]
Ok, amended the commit with a proper test. Looking good now.

**Comment by rogerleite** [comment]
Thanks @milgner!

Sorry for the super late reply! :disappointed:

**Pull request merged**
